version: '3.9'

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - 127.0.0.1:27017:27017
            - "[::1]:27017:27017"
